let stockProductos = [
    {id: 9, nombre: "Collar de respiración, Alivio inmediato",  cantidad: 1,  precio: 5800,  img: './resources/A9.jpeg'},
    {id: 10, nombre: "Tableta de limpieza universal  para cerámicas piso de baldosa,fragancia",  cantidad: 1,  precio: 5800,  img: './resources/A10.jpeg'},
    {id: 11, nombre: "Ropa para perro",  cantidad: 1,  precio: 5800,  img: './resources/A11.jpeg'},
    {id: 12, nombre: "Dispensadora  para teñir cabello",  cantidad: 1,  precio: 5800,  img: './resources/A12.jpeg'},
    {id: 13, nombre: "Cinta impermeable super pegamento para prevenir inmediatamente las fugas",  cantidad: 1,  precio: 5800,  img: './resources/A13.jpeg'},
    {id: 14, nombre: "Anillo labios De acero inoxidable",  cantidad: 1,  precio: 5800,  img: './resources/A14.jpeg'},
    {id: 15, nombre: "Desescamador de pescado",  cantidad: 1,  precio: 5800,  img: './resources/A15.jpeg'},
    {id: 16, nombre: "Granos de adhesivo para rellenar espacios",  cantidad: 1,  precio: 5800,  img: './resources/A16.jpeg'},
    {id: 17, nombre: "Capa de paraguas para cortar el cabello en forma de paraguas",  cantidad: 1,  precio: 5800,  img: './resources/A17.jpeg'},
    {id: 18, nombre: "Guantes para jardín con garras seguros para trabajo",  cantidad: 1,  precio: 5800,  img: './resources/A18.jpeg'},
    {id: 19, nombre: "Coleta para mujeres con clip de garra medidas 60 96 cm",  cantidad: 1,  precio: 5800,  img: './resources/A19.jpeg'},
    {id: 20, nombre: "Anillos dorados con elegantes piedras",  cantidad: 1,  precio: 5800,  img: './resources/A20.jpeg'},
    {id: 21, nombre: Tijeras de cocina en acero inoxidable"",  cantidad: 1,  precio: 5800,  img: './resources/A21.jpeg'},
    {id: 22, nombre: "Cepillo para zapatos multinacional",  cantidad: 1,  precio: 5800,  img: './resources/A22.jpeg'},
    {id: 23, nombre: "Pulsera elegante  con anillo",  cantidad: 1,  precio: 5800,  img: './resources/A23.jpeg'},
    {id: 24, nombre: "Accesorio nupcial de lujo  pulsera más anillo",  cantidad: 1,  precio: 5800,  img: './resources/A24.jpeg'},
    {id: 25, nombre: "Anillos con elegantes piedras",  cantidad: 1,  precio: 5800,  img: './resources/A25.jpeg'},
    {id: 26, nombre: "Colador para aceite de freir",  cantidad: 1,  precio: 5800,  img: './resources/A26.jpeg'},
    {id: 27, nombre: "Masajeador de cuello y espalda con terapia magnética",  cantidad: 1,  precio: 5800,  img: './resources/A27.jpeg'},
    {id: 28, nombre: "Reloj para hombres",  cantidad: 1,  precio: 5800,  img: './resources/A28.jpeg'},
    {id: 29, nombre: "Anillo en forma de dragón  para hombres",  cantidad: 1,  precio: 5800,  img: './resources/A29.jpeg'},
    {id: 30, nombre: "Grifo de bidé de mano para inodoro",  cantidad: 1,  precio: 5800,  img: './resources/A30.jpeg'},
    {id: 31, nombre: "Pieza ajustable  para tejer",  cantidad: 1,  precio: 5800,  img: './resources/A31.jpeg'},
    {id: 32, nombre: "Protector de dedo antiguo",  cantidad: 1,  precio: 5800,  img: './resources/A32.jpeg'},
    {id: 33, nombre: "Soporte de insiencio de reflujo de paisaje de montaña",  cantidad: 1,  precio: 5800,  img: './resources/A33.jpeg'},
    {id: 34, nombre: "Conos de insiencio  de diferente fragancia",  cantidad: 1,  precio: 5800,  img: './resources/A34.jpeg'},
    {id: 35, nombre: "Risador de pestaña eléctrico",  cantidad: 1,  precio: 5800,  img: './resources/A35.jpeg'},
    {id: 36, nombre: "Cepillo de ducha en silicona",  cantidad: 1,  precio: 5800,  img: './resources/A36.jpeg'},
    {id: 37, nombre: "Cepillo  de aseo",  cantidad: 1,  precio: 5800,  img: './resources/37.jpeg'},
    {id: 38, nombre: "Pistola de agua para lavar motocicletas",  cantidad: 1,  precio: 5800,  img: './resources/A38.jpeg'},   
]
